import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Scoring Disclaimer",
  description: "Important information about CelpipReady's AI-generated scores and its relationship to the official CELPIP test."
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-2xl mx-auto">

        <div className="mb-8">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-700">← Back to home</Link>
          <h1 className="text-3xl font-bold text-slate-900 mt-4">AI Scoring Disclaimer</h1>
          <p className="text-slate-400 text-sm mt-2">Last updated: March 2026</p>
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 mb-8">
          <p className="text-sm font-semibold text-amber-800 mb-1">Important Notice</p>
          <p className="text-sm text-amber-700">
            CelpipReady is an independent practice platform. It is not affiliated with, endorsed by,
            or connected to Paragon Testing Enterprises or the official CELPIP test program.
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-6 space-y-6 text-sm text-slate-600 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">AI Scores Are for Practice Only</h2>
            <p>
              Scores generated by CelpipReady are produced by an AI model (Google Gemini) and are intended
              solely for practice and self-assessment purposes. They do not represent, predict, or guarantee
              your performance on the official CELPIP exam.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">Not Official CELPIP Scores</h2>
            <p>
              CelpipReady does not administer official CELPIP tests. Only Paragon Testing Enterprises
              and its authorized partners can issue official CELPIP scores. Scores from CelpipReady
              cannot be submitted to Immigration, Refugees and Citizenship Canada (IRCC), provincial
              nominee programs, professional licensing bodies, or any other institution that requires
              official language test results.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">Trademark Notice</h2>
            <p>
              CELPIP® is a registered trademark of Paragon Testing Enterprises. The Canadian English
              Language Proficiency Index Program (CELPIP) is owned and administered by Paragon Testing
              Enterprises, a subsidiary of the University of British Columbia. CelpipReady has no
              affiliation with Paragon Testing Enterprises and does not represent or act on behalf of
              Paragon Testing in any capacity.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">Limitations of AI Evaluation</h2>
            <p>
              AI-generated writing and speaking scores are approximations based on linguistic patterns and
              machine learning models. They may not fully reflect the nuanced human judgment used by
              certified CELPIP raters. Feedback is generated automatically and has not been reviewed or
              validated by any accredited language assessment organization.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">Audio Data</h2>
            <p>
              Speaking responses are temporarily uploaded to Cloudinary for AI processing and are
              automatically deleted after 30 days. We do not share your audio recordings with third
              parties beyond what is necessary to provide the scoring service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">No Warranties</h2>
            <p>
              CelpipReady provides this service on an &ldquo;as is&rdquo; basis. We make no warranties,
              express or implied, regarding the accuracy, reliability, or suitability of AI-generated
              scores for any particular purpose. Use of this platform is at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-2">Book the Official CELPIP Test</h2>
            <p>
              To take the official CELPIP exam and receive scores accepted for immigration and
              professional purposes, please visit the official CELPIP website at{" "}
              <a
                href="https://www.celpip.ca"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 underline hover:text-blue-800"
              >
                www.celpip.ca
              </a>.
            </p>
          </section>

        </div>

        <p className="text-xs text-slate-400 text-center mt-8">
          Questions?{" "}
          <Link href="/contact" className="underline hover:text-slate-600">Contact us</Link>
          {" "}or email{" "}
          <a href="mailto:hello@celpipready.com" className="underline hover:text-slate-600">
            hello@celpipready.com
          </a>
        </p>

      </div>
    </div>
  );
}
